# Generated by Django 3.2.3 on 2021-06-21 15:51

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20210620_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stud',
            name='contact',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
