# Generated by Django 3.2.3 on 2021-06-27 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_stud_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='stud',
            name='auth_token',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='stud',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
